# -*- coding: utf-8 -*-
"""ConvertGeojsonToSHP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hz2p2gLpzdbcvAYy-WMiP9341CcOOAHW
"""

pip install geopandas

import geopandas as gpd
import glob
import os

ws = input('Папка geojson файлов')
path = input('Папка для сохранения SHP')
files = glob.glob(ws + '/*.geojson')

#print(files)
#print(len(files))

for filename in files:
  file_name = os.path.basename(filename)
  a = os.path.splitext(file_name)[0]
  df = gpd.read_file(filename)
  shp_file_path = os.path.join(path,a +'.shp')
  print(shp_file_path)
  df.to_file(shp_file_path)
